language: cpp

jobs:
  include:
    - os: linux
      dist: bionic
      compiler: gcc
      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libxrandr-dev 
            - libxinerama-dev
            - libxcursor-dev
            - libxi-dev
            - libxext-dev
            - xorg-dev

    - os: linux
      dist: bionic
      compiler: clang
      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libxrandr-dev 
            - libxinerama-dev
            - libxcursor-dev
            - libxi-dev
            - libxext-dev
            - xorg-dev

    - os: osx 
      osx_image: xcode12.5

script:
  - pip install conan
  - conan profile detect
  - sh build.sh -test
