language: cpp

jobs:
  include:
    - os: linux
      dist: bionic
      compiler: gcc
      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libxrandr-dev 
            - libxinerama-dev
            - libxcursor-dev
            - libxi-dev
            - libxext-dev

    - os: linux
      dist: bionic
      compiler: clang
      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libxrandr-dev 
            - libxinerama-dev
            - libxcursor-dev
            - libxi-dev
            - libxext-dev

    - os: osx 
      osx_image: xcode12.5

script:
  - mkdir deps
  - cd deps
  - git clone --depth 1 --branch 3.3.4 https://github.com/glfw/glfw
  - git clone --depth 1 --branch v3.1.0 https://github.com/cginternals/glbinding
  - git clone --depth 1 --branch v2.13.7 https://github.com/catchorg/Catch2
  - cd ..
  - mkdir build
  - cd build
  - cmake -G 'Unix Makefiles' -std=c++17 .. && cmake --build . && make test
