language: cpp

jobs:
  include:
    - os: linux
      dist: xenial
      compiler: gcc
      env: COMPILER=Unix Makefiles
      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-7
            - g++-7
            - xorg-dev

    - os: linux
      dist: xenial
      compiler: clang
      env: COMPILER=Unix Makefiles
      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - xorg-dev
            - libc++

    - os: osx 
      env: COMPILER=Unix Makefiles
      osx_image: xcode10.1

script:
  - sh build.sh -c $COMPILER -clobber -test
