language: cpp

jobs:
  include:
    - os: linux
      dist: bionic
      compiler: gcc
      env: COMPILER=g++-7
      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-7
            - g++-7
            - xorg-dev

    - os: linux
      dist: bionic
      compiler: clang
      env: COMPILER=clang++
      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7

    - os: osx 
      osx_image: xcode13
      env: COMPILER=clang++

script:
  - mkdir deps
  - cd deps
  - git clone --depth 1 --branch 3.3.4 https://github.com/glfw/glfw
  - git clone --depth 1 --branch v3.1.0 https://github.com/cginternals/glbinding
  - git clone --depth 1 --branch v2.13.7 https://github.com/catchorg/Catch2
  - cd ..
  - mkdir build
  - cd build
  - cmake -G 'Unix Makefiles' -std=c++17 -DCMAKE_CXX_COMPILER=$COMPILER .. && cmake --build . && make test
