version: 2.1
jobs:
  build-and-test:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: Install Conan
          command: pip install --user conan
      - run:
          name: Detect Conan Profile
          command: conan profile detect
      - run:
          name: Build and Test
          command: sh build.sh -test
workflows:
  say-hello-workflow:
    jobs:
      - build-and-test
